version: '3.8'

services:
  # Full stack application (production ready)
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLIENT_URL=http://localhost:5000
    volumes:
      - ./server/.env.production:/app/.env
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - blood-bank-network

  # MongoDB service (for local development/testing)
  mongodb:
    image: mongo:7.0
    container_name: blood-bank-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - blood-bank-network

volumes:
  mongodb_data:

networks:
  blood-bank-network:
    driver: bridge
