version: '3.8'

services:
  # Backend service for development
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLIENT_URL=http://localhost:5173
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongodb
    networks:
      - blood-bank-network

  # Frontend service for development
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - blood-bank-network

  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: blood-bank-mongo-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - blood-bank-network

volumes:
  mongodb_dev_data:

networks:
  blood-bank-network:
    driver: bridge
